# Copyright (c) 2020, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM microsoft/mssql-server-linux

ENV SA_PASSWORD=Test123#
ENV ACCEPT_EULA=Y

# RUN mkdir -p /usr/work
# WORKDIR /usr/work

# COPY .  /usr/work/

# RUN chmod +x /usr/work/import-data.sh

# # EXPOSE 1433
# CMD /bin/bash ./entrypoint.sh